city = input("Enter A City Name: ")
print("Your City Name IS: ", city)
if "mathura" == city.lower():
    print("Bhagwan ji ka dawar  ")
    print("1 : Prem Mandir, Vrindavan")
    print("2 : Shree Dwarikadhish Temple, Mathura")
    print("3 : Vishram Ghat")
    print("4 : Government Museum, Mathura")
    print("5 : hri Bhuteshwar Mahadev Mandir, Mathura")
    print("6 : Prem Mandir, Vrindavan")
    print("7 : Baba Jai Guru Dev Mandir")
    print("8 : Shri Raman Bihari Ji Temple, Gokul")
    print("9 : Potra kund")
    print("10 : Maa Vaishno Devi Dham, Vrindavan")
    print("11 : Kusum Sarovar, Govardhan")
    print("12 : Kans Quila, Mathura")
    print("13 : Shri Nand Yashoda Bhawan, Gokul Dham")
    print("14 : Radhavallabh Lal Ji Temple, Vrindavan")
    print("15 : Shri Dauji Maharaj Temple, Mathura")
    print("16 : Shri Chamunda Devi Mandir")
    print("17 : Rang ji ka Mandir")
    print("18 : Tilak Dwar")
elif "ayodhya" == city.lower():
    print("Bhagwan ji ka dawar  ")
    print("1. Ram Janmabhoomi")
    print("2. Hanuman Garhi, Ayodhya")
    print("3. Kanak Bhawan")
    print("4. Nageshwarnath Temple")
    print("5. Gulab Bari")
    print("6. Treta Ke Thakur")
    print("7. Choti Chawni")
    print("8. Sita Ki Rasoi")
    print("9. Tulsi Smarak Bhawan")
    print("10. Bahu Begum Ka Maqbara")
    print("11. Raja Mandir")
    print("12. Ram Katha Park")
    print("13. Moti Mahal")
    print("14. Dashrath Bhavan")
    print("16. Mani Parbat")
elif "jaipur" == city.lower():
    print("Top 5 popular place ")
    print("1 : City Palace")
    print("2 : Amber Fort")
    print("3 : Hawa Mahal")
    print("4 : Nahargarh Fort")
    print("5 : Jal Mahal")
elif "jodhpur" == city.lower():
    print("Top 5 popular place ")
    print("1 : Mehrangarh Fort")
    print("2 : Umaid Bhawan Palace")
    print("3 : Jaswant Thada")
    print("4 : Ghanta Ghar Jodhpur")
    print("5 : Rao Jodha Desert Rock Park")
    
else:
    print("Data not Found")
